language: objective-c
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- rake install
script:
- pod lib lint --quick
- rake test
after_success:
- rake report
